name: ornaguide
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  image_picker: ^1.0.4
  http: ^1.2.0
  firebase_storage: ^12.4.5
  flutter_markdown: 0.6.14
  google_fonts: ^6.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/plant1.png
    - assets/plant2.png
    - assets/plant3.jpg